# Netlify Configuration File
# Place this file in the root of your project

[build]
  # Build command (adjust based on your package.json scripts)
  command = "npm run build"
  
  # Directory where your build output goes (adjust if different)
  publish = "dist"
  
  # Set environment to production
  environment = { NODE_VERSION = "18" }

# Netlify Forms work automatically without a plugin!
# The plugin is only needed for advanced features

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"